spring:
  application:
    name: customer-service
  datasurce: 
    url: jdbc:mysql://localhost:3306/customer_master
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
    hibernate:
      ddl-auto: none
    show-sql: false
